// constants/auditActions.js

export const AUDIT_ACTIONS = Object.freeze({
  SONG_APPROVED: "SONG_APPROVED",
  SONG_REJECTED: "SONG_REJECTED",
  SONG_BLOCKED: "SONG_BLOCKED",
  SONG_UNBLOCKED: "SONG_UNBLOCKED",
  SONG_RESUBMITTED: "SONG_RESUBMITTED",
});

export const AUDIT_MODULES = Object.freeze({
  SONGS: "SONGS",
  USERS: "USERS",
  AUTH: "AUTH",
});

export const NOTIFICATION_TYPES = Object.freeze({
  SYSTEM: "SYSTEM",
  ACCOUNT: "ACCOUNT",
  SECURITY: "SECURITY",
  SONG_APPROVED: "SONG_APPROVED",
  SONG_REJECTED: "SONG_REJECTED",
  SONG_BLOCKED: "SONG_BLOCKED",
  PLAYLIST: "PLAYLIST",
  FOLLOW: "FOLLOW",
  REPORT: "REPORT",
  ADMIN: "ADMIN",
  ARTIST: "ARTIST",
  GENERAL: "GENERAL",
});

export const NOTIFICATION_PRIORITIES = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
});

export const NOTIFICATION_TYPE_LIST = Object.freeze(Object.values(NOTIFICATION_TYPES));
export const NOTIFICATION_PRIORITY_LIST = Object.freeze(Object.values(NOTIFICATION_PRIORITIES));
